; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25831.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\David\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
